name: auto-create-branch-pull-request-for-upstream

on:
  push:
    branches:
      - '**'  # All branches

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      is-fork: ${{ steps.check.outputs.is-fork }}
    steps:
      - name: Check if this is the fork
        id: check
        run: |
          echo "🧠 Repo: ${{ github.repository }}"
          if [ "${{ github.repository_owner }}" == "RichLewis007" ]; then
            echo "is-fork=true" >> $GITHUB_OUTPUT
            echo "✅ Proceeding in fork"
          else
            echo "is-fork=false" >> $GITHUB_OUTPUT
            echo "🚫 Skipping: Not the fork"
          fi

  create-pr:
    needs: precheck
    if: needs.precheck.outputs.is-fork == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Add upstream remote
        run: git remote add upstream https://github.com/MakerFriends/educational-site-creation.git

      - name: Check if Pull Request is needed
        id: check-pr
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "🌿 Branch: $BRANCH_NAME"

          IGNORE_BRANCHES=("gh-pages" "sync-fork")
          for IGNORE in "${IGNORE_BRANCHES[@]}"; do
            if [[ "$BRANCH_NAME" == "$IGNORE" ]]; then
              echo "🚫 Skipping PR creation for ignored branch: $BRANCH_NAME"
              exit 0
            fi
          done

          git fetch origin
          git fetch upstream

          if [ "$BRANCH_NAME" == "main" ]; then
            COUNT=$(git rev-list --count remotes/upstream/main..remotes/origin/main)
            echo "🔍 Commits to PR: $COUNT"
            if [ "$COUNT" -eq 0 ]; then
              echo "✅ No changes to PR — exiting"
              exit 0
            fi
            git log remotes/upstream/main..remotes/origin/main --oneline
          fi

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.FORKED_GH_TOKEN }}
        run: |
          if: env.FORKED_GH_TOKEN != '' # prevent running in upstream
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            echo "📬 Creating PR for: $BRANCH_NAME"
            gh auth status
            gh pr create \
              --title "Automated Pull Request: $BRANCH_NAME" \
              --body "Automated Pull Request from ${{ github.repository_owner }} branch $BRANCH_NAME." \
              --label "automerge" \ 
              --base main \
              --head "${{ github.repository_owner }}:$BRANCH_NAME" \
              --repo MakerFriends/educational-site-creation || echo "ℹ️ PR already exists or failed silently"
