name: sync-fork-with-upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

# Immediately cancel workflow if this is not the fork
jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel if not running in fork
        run: |
          echo "🔍 Running in repo: ${{ github.repository }}"
          if [ "${{ github.repository_owner }}" != "RichLewis007" ]; then
            echo "⛔ Exiting: This workflow is only for the fork."
            exit 0
          fi

  sync:
    needs: precheck
    if: ${{ github.repository_owner == 'RichLewis007' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/MakerFriends/educational-site-creation.git
          git fetch upstream

      - name: Merge upstream/main into origin/main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Already up to date"

      - name: Push changes back to origin
        env:
          GH_TOKEN: ${{ secrets.FORK_GH_TOKEN2 }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
