name: GH Token Test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-gh-auth:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FORK_GH_TOKEN4 }}  # Map your custom token to GH_TOKEN
    steps:
      - name: Check GitHub CLI version
        run: gh --version

      - name: Confirm GitHub auth status
        run: gh auth status

      - name: List last 3 PRs from this repo
        run: gh pr list --limit 3 --state all --json title,author,createdAt
