name: upstream-auto-merge-PR

# Tests: This workflow assumes your CI passes. Add "statusChecks" if you want to wait for specific checks to pass.
# Security: Auto-merging from forks is risky. Keep allowForks: false unless you're handling validations elsewhere.
# Bot Access: GITHUB_TOKEN has limited access; for advanced workflows (e.g., repo in orgs), use a fine-grained PAT.

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:  # Allow manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
    
    # env:
    #   OWNER: ${{ github.repository_owner }}
    # run: echo ${{ github.repository_owner }}
    # Prevents execution in forks or untrusted repositories
    # if: "$OWNER" == "MakerFriends"

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Confirm GH_TOKEN is set
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ GH_TOKEN is missing. Please set the secret correctly."
            exit 1
          else
            echo "✅ GH_TOKEN appears to be set."
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show auth status
        run: gh auth status

      - name: Debug PR context
        run: |
          echo "🔗 Repo: $GITHUB_REPOSITORY"
          echo "🔢 PR #: ${{ github.event.pull_request.number }}"
          echo "🔤 Head: ${{ github.event.pull_request.head.ref }}"
          echo "🧬 Base: ${{ github.event.pull_request.base.ref }}"
          
      - name: Show repo owner
        env:
          OWNER: ${{ github.repository_owner }}
        run: echo "$OWNER"

      - name: Debug: Print PR details
        run: |
          echo "🔎 PR Number: ${{ github.event.pull_request.number }}"
          gh pr view ${{ github.event.pull_request.number }} \
            --json mergeable,state,title,headRefName,baseRefName,labels \
            --jq '.'
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}


      - name: Auto-merge PRs from trusted sources
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN : "$GH_TOKEN" 
          # ${{ secrets.UPSTREAM_GH_TOKEN }}  # Or secrets.GITHUB_TOKEN
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          AUTHOR_EMAIL: bot@github.com
          AUTHOR_NAME: Auto Merge Bot
          ALLOW_FORKS: true # ⚠️ Strongly recommended: disallow fork merges unless you handle validation
          REVIEWERS: '' # No reviewers required
          BLOCKING_LABELS: do-not-merge
          REQUIRED_LABELS: automerge
