name: upstream-auto-merge-PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      pr_number:
        description: "Optional PR number to manually merge (for testing only)"
        required: false

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}

    steps:
      - name: Confirm GH_TOKEN is set
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ GH_TOKEN is missing. Please set the UPSTREAM_GH_TOKEN secret."
            exit 1
          fi
          echo "✅ GH_TOKEN is set."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "pull_request_target" ]; then
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ inputs.pr_number }}" ]; then
            echo "PR_NUMBER=${{ inputs.pr_number }}" >> "$GITHUB_OUTPUT"
          else
            echo "❌ No PR number found. Exiting."
            exit 0
          fi

      - name: Evaluate and auto-merge PR
        run: |
          PR_NUM="${{ steps.pr.outputs.PR_NUMBER }}"
          echo "🔍 Evaluating PR #$PR_NUM"

          PR_JSON=$(gh pr view "$PR_NUM" \
            --json number,title,state,mergeable,labels,isCrossRepository \
            --jq '.')

          echo "$PR_JSON" | jq '.'

          MERGEABLE=$(echo "$PR_JSON" | jq -r '.mergeable')
          STATE=$(echo "$PR_JSON" | jq -r '.state')
          LABELS=$(echo "$PR_JSON" | jq -r '[.labels[].name] | join(", ")')
          IS_FORK=$(echo "$PR_JSON" | jq -r '.isCrossRepository')

          echo "📄 State: $STATE"
          echo "📎 Labels: $LABELS"
          echo "🔀 Mergeable: $MERGEABLE"
          echo "🔗 From fork: $IS_FORK"

          if [[ "$STATE" != "OPEN" ]]; then
            echo "❌ PR is not open. Skipping."
            exit 0
          fi

          if [[ "$LABELS" != *"automerge"* ]]; then
            echo "❌ PR does not have 'automerge' label. Skipping."
            exit 0
          fi

          if [[ "$LABELS" == *"do-not-merge"* ]]; then
            echo "❌ PR has 'do-not-merge' label. Skipping."
            exit 0
          fi

          if [[ "$MERGEABLE" != "MERGEABLE" ]]; then
            echo "❌ PR is not currently mergeable (status: $MERGEABLE). Skipping."
            exit 0
          fi

          echo "✅ All conditions met. Proceeding to merge..."
          gh pr merge "$PR_NUM" \
            --squash \
            --delete-branch \
            --subject "Auto-merged PR #$PR_NUM" \
            --body "✅ Auto-merged because all merge conditions were met."
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
