name: upstream-auto-merge-PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      pr_number:
        description: "Optional PR number to manually merge (for testing only)"
        required: false

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}

    steps:
      - name: Confirm GH_TOKEN is set
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ GH_TOKEN is missing. Please set the UPSTREAM_GH_TOKEN secret."
            exit 1
          fi
          echo "✅ GH_TOKEN is set."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show context info
        run: |
          echo "🔧 Event name: ${{ github.event_name }}"
          echo "🔢 PR number from event: ${{ github.event.pull_request.number }}"
          echo "🔢 PR number from input: ${{ inputs.pr_number }}"

      - name: View PR details (if pull_request_target)
        if: github.event_name == 'pull_request_target'
        run: |
          gh pr view ${{ github.event.pull_request.number }} \
            --json number,title,state,mergeable,headRefName,baseRefName,author,labels,isCrossRepository \
            --jq '.'
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}

      - name: Auto-merge PR (event-triggered)
        if: github.event_name == 'pull_request_target'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          AUTHOR_NAME: Auto Merge Bot
          AUTHOR_EMAIL: bot@github.com
          REQUIRED_LABELS: automerge
          BLOCKING_LABELS: do-not-merge
          ALLOW_FORKS: true

      - name: Manually merge PR (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch' && inputs.pr_number != ''
        run: |
          echo "🔁 Attempting manual merge of PR #${{ inputs.pr_number }}"

          gh pr view ${{ inputs.pr_number }} \
            --json number,title,state,mergeable,labels \
            --jq '.'

          gh pr merge ${{ inputs.pr_number }} \
            --squash \
            --delete-branch \
            --subject "Auto-merged PR #${{ inputs.pr_number }}" \
            --body "Manually triggered merge via workflow_dispatch"
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
